/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package networking;

import org.checkerframework.common.value.qual.IntVal;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.io.ObjectInputStream.GetField;

class ServerTest {
    @Test void ServerTestHasPort() throws IOException {
        Server classUnderTest = new Server(5050);
        assertNotNull(classUnderTest.getPriority(), "app should have a greeting");
    }
}
